# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Bowen Street Book Club"
description: > 
  We read a chapter or two each week and fangirl out in the comments section of my weekly recap & review hosted online in this nerdy book club.
email: jakecooperdesign@gmail.com
logo: /assets/img/branding/Bowen-Street-Book-Club-Logo-Image.jpg

url: "http://bowenstreetbookclub.com"
baseurl: ""
twitter:
  username: bowenstbookclub
facebook:
  app_id: 1062263850493715
  publisher: 150265972061629
author: 
  twitter: bowenstbookclub


include: ["_pages"]

exclude: 
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
 - node_modules

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
  stype: compressed

collections:
  books:
    output: true
    permalink: /books/:path/
  recaps:
    output: true
    permalink: /recaps/:path/

defaults:
  - 
    scope: 
      path: ""
    values:
      image: /assets/img/branding/Bowen-Street-Book-Club-Logo-Image.jpg
  - 
    scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - 
    scope:
      path: ""
      type: "recaps"
    values:
      layout: "recap" 