# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Bowen Street Book Club"
email: jakecooperdesign@gmail.com
description: > 
  We read a chapter or two each week and fangirl out in the comments section of my weekly recap & review hosted online.
baseurl: ""
url: "http://bowenstreetbookclub.com"

include: ["_pages"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

collections:
  books:
    output: true
    permalink: /books/:path/
  recaps:
    output: true
    permalink: /recaps/:path/

defaults:
  - 
    scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - 
    scope:
      path: ""
      type: "recaps"
    values:
      layout: "recap" 